//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVD.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int id_cheque { get; set; }
        public int id_rent { get; set; }
        public int id_film { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Rent Rent { get; set; }
    }
}
